import type { RuntimeConfigSchema, RuntimeField } from "@minions/shared";

const fields: RuntimeField[] = [
  {
    key: "dagMaxConcurrent",
    label: "DAG max concurrent",
    description: "Maximum number of DAG nodes running in parallel",
    type: "number",
    default: 3,
    min: 1,
    max: 32,
    step: 1,
    group: "execution",
    applies: "live",
  },
  {
    key: "loopMaxTotal",
    label: "Loop max total",
    description: "Maximum total loop sessions allowed",
    type: "number",
    default: 20,
    min: 0,
    max: 100,
    step: 1,
    group: "loops",
    applies: "live",
  },
  {
    key: "loopReservedInteractive",
    label: "Loop reserved interactive slots",
    description: "Slots reserved for interactive sessions (loops cannot use them)",
    type: "number",
    default: 4,
    min: 0,
    max: 20,
    step: 1,
    group: "loops",
    applies: "live",
  },
  {
    key: "ciSelfHealMaxAttempts",
    label: "CI self-heal max attempts",
    description:
      "When CI fails on an auto-landed PR, replay the failure into the same session up to this many times. 0 disables self-heal.",
    type: "number",
    default: 3,
    min: 0,
    max: 20,
    step: 1,
    group: "ci",
    applies: "live",
  },
  {
    key: "quotaRetryBudget",
    label: "Quota retry budget",
    description: "Number of retries on quota exhaustion before failing",
    type: "number",
    default: 3,
    min: 0,
    max: 10,
    step: 1,
    group: "execution",
    applies: "live",
  },
  {
    key: "memoryMcpEnabled",
    label: "Memory MCP enabled",
    description: "Enable the in-process memory MCP server",
    type: "boolean",
    default: true,
    group: "memory",
    applies: "restart",
  },
  {
    key: "qualityTimeoutMs",
    label: "Quality check timeout (ms)",
    description: "Maximum time for each quality check command",
    type: "number",
    default: 300000,
    min: 5000,
    max: 3600000,
    step: 1000,
    group: "quality",
    applies: "live",
  },
  {
    key: "pushNotifyOnAttention",
    label: "Push notify on attention",
    description: "Send push notifications when a session needs attention",
    type: "boolean",
    default: true,
    group: "notifications",
    applies: "live",
  },
  {
    key: "pushNotifyOnResourceAlert",
    label: "Push notify on resource alert",
    description:
      "Send push notifications when memory or disk usage crosses the configured threshold",
    type: "boolean",
    default: true,
    group: "notifications",
    applies: "live",
  },
  {
    key: "resourceMemoryAlertPct",
    label: "Memory alert threshold (%)",
    description:
      "Alert when memory usage exceeds this percentage of the cgroup limit",
    type: "number",
    default: 90,
    min: 50,
    max: 99,
    step: 1,
    group: "notifications",
    applies: "live",
  },
  {
    key: "resourceDiskAlertPct",
    label: "Disk alert threshold (%)",
    description:
      "Alert when disk usage exceeds this percentage of the workspace volume",
    type: "number",
    default: 90,
    min: 50,
    max: 99,
    step: 1,
    group: "notifications",
    applies: "live",
  },
  {
    key: "resourceAlertCooldownMin",
    label: "Resource alert cooldown (minutes)",
    description: "Minimum minutes between alerts for the same resource.",
    type: "number",
    default: 60,
    min: 5,
    max: 1440,
    step: 5,
    group: "notifications",
    applies: "live",
  },
  {
    key: "judgeRubricDefault",
    label: "Default judge rubric",
    description: "Default rubric for variant judge evaluation",
    type: "string",
    default: "Favor correctness first, then minimality, then clarity.",
    group: "variants",
    applies: "live",
  },
  {
    key: "sseHeartbeatSec",
    label: "SSE heartbeat interval (seconds)",
    description: "How often to send SSE ping frames",
    type: "number",
    default: 25,
    min: 5,
    max: 120,
    step: 1,
    group: "transport",
    requiresRestart: true,
    applies: "restart",
  },
  {
    key: "rebaseAutoResolverEnabled",
    label: "Rebase auto-resolver enabled",
    description: "Automatically spawn a rebase resolver session on conflict",
    type: "boolean",
    default: true,
    group: "execution",
    applies: "live",
  },
  {
    key: "editorOpenEnabled",
    label: "Editor open enabled",
    description:
      "Allow the session header's 'Open in editor' button to spawn a local editor process pointed at the worktree. Security-sensitive — only enable when the engine runs on a trusted host.",
    type: "boolean",
    default: true,
    group: "execution",
    applies: "live",
  },
  {
    key: "landingDefaultStrategy",
    label: "Default landing strategy",
    description: "Default merge strategy when landing a session",
    type: "enum",
    default: "squash",
    enumValues: ["merge", "squash", "rebase"],
    group: "execution",
    applies: "live",
  },
  {
    key: "autoCommitOnCompletion",
    label: "Auto-commit on completion",
    description: "Automatically commit worktree changes when a session completes successfully",
    type: "boolean",
    default: true,
    group: "execution",
    applies: "live",
  },
  {
    key: "autoLandOnCompletion",
    label: "Auto-land on completion",
    description: "Automatically push and open a PR for task sessions that complete with new commits",
    type: "boolean",
    default: true,
    group: "execution",
    applies: "live",
  },
  {
    key: "autoMergeOnGreen",
    label: "Auto-merge PR on green CI",
    description:
      "Automatically squash-merge a PR once all CI checks pass, no reviewer has requested changes, and the PR is mergeable. Pairs with CI self-heal so a successful retry lands without operator action.",
    type: "boolean",
    default: false,
    group: "autonomy",
    applies: "live",
  },
  {
    key: "autoLandReadyOnGreen",
    label: "Auto-land session when CI passes and readiness is ready",
    description:
      "When CI polling detects a session whose readiness flips to 'ready', automatically squash-merge it via the engine landing path. Requires autoMergeOnGreen to be disabled to avoid double-merge; designed for unattended Docker.",
    type: "boolean",
    default: false,
    group: "autonomy",
    applies: "live",
  },
  {
    key: "autoFixCiOnFailure",
    label: "Auto-spawn fix-CI sub-session on CI failure",
    description:
      "When CI fails on a session with an open PR, automatically spawn a child task session to investigate and fix the failure. Skips sessions already of kind 'fix-ci' to avoid recursion.",
    type: "boolean",
    default: false,
    group: "autonomy",
    applies: "live",
  },
  {
    key: "defaultSelfHealCi",
    label: "Default new sessions to CI self-heal",
    description:
      "Set selfHealCi=true on every new task session by default, so a CI failure replays the failure as a reply to the same session (no spawned children). Caller-provided metadata.selfHealCi always wins, including explicit false.",
    type: "boolean",
    default: false,
    group: "autonomy",
    applies: "live",
  },
  {
    key: "admissionUnlimited",
    label: "Admission unlimited (disable caps)",
    description:
      "Disable all admission caps. The engine will accept any number of concurrent sessions; only the OS bounds resource usage. Use only when host has plenty of CPU/RAM.",
    type: "boolean",
    default: false,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionTotalSlots",
    label: "Admission total slots",
    description: "Maximum total concurrent sessions across all classes",
    type: "number",
    default: 8,
    min: 1,
    max: 64,
    step: 1,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionReservedInteractive",
    label: "Admission reserved interactive",
    description: "Slots reserved exclusively for interactive sessions (task, ship)",
    type: "number",
    default: 2,
    min: 0,
    max: 32,
    step: 1,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionLoopCap",
    label: "Admission loop cap",
    description: "Hard cap on concurrent autonomous loop sessions",
    type: "number",
    default: 4,
    min: 0,
    max: 32,
    step: 1,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionDagCap",
    label: "Admission DAG task cap",
    description: "Hard cap on concurrent DAG task sessions",
    type: "number",
    default: 4,
    min: 0,
    max: 32,
    step: 1,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionBackgroundCap",
    label: "Admission background cap",
    description: "Hard cap on concurrent background sessions (review, rebase-resolver, etc.)",
    type: "number",
    default: 2,
    min: 0,
    max: 32,
    step: 1,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionDiskFloorBytes",
    label: "Admission disk floor (bytes)",
    description:
      "Refuse admission when free disk on the workspace volume is below this many bytes. Applies even when admissionUnlimited is true.",
    type: "number",
    default: 5_000_000_000,
    min: 1_000_000_000,
    max: 1_000_000_000_000,
    step: 100_000_000,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionMemoryFloorBytes",
    label: "Admission memory floor (bytes)",
    description:
      "Refuse admission when free memory is below this many bytes. Applies even when admissionUnlimited is true.",
    type: "number",
    default: 1_000_000_000,
    min: 100_000_000,
    max: 100_000_000_000,
    step: 100_000_000,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionEventLoopLagCeilingMs",
    label: "Admission event-loop lag ceiling (ms)",
    description:
      "Refuse admission when the engine's event-loop lag exceeds this many milliseconds. Applies even when admissionUnlimited is true.",
    type: "number",
    default: 250,
    min: 50,
    max: 10_000,
    step: 10,
    group: "admission",
    applies: "live",
  },
  {
    key: "admissionMaxClaudeProcesses",
    label: "Admission max active claude processes",
    description:
      "Refuse admission when the number of running claude subprocesses exceeds this. Applies even when admissionUnlimited is true.",
    type: "number",
    default: 12,
    min: 1,
    max: 256,
    step: 1,
    group: "admission",
    applies: "live",
  },
  {
    key: "defaultSessionBudgetUsd",
    label: "Default session cost cap (USD)",
    description: "Seeds costBudgetUsd on new sessions that do not specify one. 0 disables.",
    type: "number",
    default: 0,
    min: 0,
    max: 1000,
    step: 0.01,
    group: "budget",
    applies: "live",
  },
  {
    key: "policyHooksEnabled",
    label: "Policy hooks enabled",
    description: "Inject Bash safety hooks and Stop reminder into per-session Claude Code settings",
    type: "boolean",
    default: true,
    group: "execution",
    applies: "restart",
  },
  {
    key: "autoCleanupEnabled",
    label: "Auto cleanup enabled",
    description:
      "Run a daily background job that deletes old completed/failed/cancelled sessions to reclaim disk used by worktrees and transcripts.",
    type: "boolean",
    default: true,
    group: "maintenance",
    applies: "live",
  },
  {
    key: "cleanupOlderThanDays",
    label: "Cleanup age threshold (days)",
    description:
      "Sessions whose completedAt is older than this many days are eligible for the daily auto-cleanup. Sessions with open PRs or in active DAGs are always skipped.",
    type: "number",
    default: 7,
    min: 1,
    max: 365,
    step: 1,
    group: "maintenance",
    applies: "live",
  },
  {
    key: "cleanupHourLocal",
    label: "Cleanup hour (local time, 0-23)",
    description:
      "Hour of the local day to run the cleanup job. Restart the engine to pick up changes.",
    type: "number",
    default: 3,
    min: 0,
    max: 23,
    step: 1,
    group: "maintenance",
    applies: "restart",
  },
  {
    key: "crashLogDir",
    label: "Crash log directory",
    type: "string",
    default: "~/.minions/crashes",
    group: "execution",
    applies: "restart",
  },
  {
    key: "overnightProfile",
    label: "Enable overnight profile",
    description: "Apply conservative defaults for unattended overnight runs.",
    type: "boolean",
    default: false,
    group: "overnight",
    applies: "live",
  },
  {
    key: "overnightAdmissionTotalSlots",
    label: "Overnight total slots",
    type: "number",
    default: 4,
    min: 1,
    max: 32,
    step: 1,
    group: "overnight",
    applies: "live",
  },
  {
    key: "overnightCleanupRetentionDays",
    label: "Overnight cleanup retention (days)",
    type: "number",
    default: 3,
    min: 1,
    max: 30,
    step: 1,
    group: "overnight",
    applies: "live",
  },
  {
    key: "overnightCiSelfHealMaxAttempts",
    label: "Overnight CI self-heal max attempts",
    type: "number",
    default: 3,
    min: 1,
    max: 10,
    step: 1,
    group: "overnight",
    applies: "live",
  },
  {
    key: "overnightSpawnTimeoutMs",
    label: "Overnight spawn timeout (ms)",
    type: "number",
    default: 180000,
    min: 30000,
    max: 600000,
    step: 1000,
    group: "overnight",
    applies: "restart",
  },
  {
    key: "automationTickSec",
    label: "Automation runner tick (seconds)",
    description:
      "How often the automation job runner polls for due jobs. Restart the engine to apply changes.",
    type: "number",
    default: 5,
    min: 1,
    max: 60,
    step: 1,
    group: "execution",
    applies: "restart",
  },
  {
    key: "bootRecovery",
    label: "Boot recovery enabled",
    description:
      "On engine restart, scan ship sessions whose stage was think/plan/verify and raise an attention flag if the session could not be auto-resumed. DAG-stage ships rely on the existing watchdog. Disable to silence the boot scan.",
    type: "boolean",
    default: true,
    group: "execution",
    applies: "restart",
  },
];

export const runtimeConfigSchema: RuntimeConfigSchema = {
  groups: [
    { id: "execution", label: "Execution" },
    { id: "autonomy", label: "Autonomy" },
    { id: "loops", label: "Loops" },
    { id: "ci", label: "CI" },
    { id: "quality", label: "Quality" },
    { id: "memory", label: "Memory" },
    { id: "notifications", label: "Notifications" },
    { id: "variants", label: "Variants" },
    { id: "transport", label: "Transport" },
    { id: "admission", label: "Admission" },
    { id: "budget", label: "Budget" },
    { id: "maintenance", label: "Maintenance" },
    { id: "overnight", label: "Overnight self-dogfood" },
  ],
  fields,
};
