import type { RuntimeConfigSchema, RuntimeField } from "@minions/shared";

const fields: RuntimeField[] = [
  {
    key: "dagMaxConcurrent",
    label: "DAG max concurrent",
    description: "Maximum number of DAG nodes running in parallel",
    type: "number",
    default: 3,
    min: 1,
    max: 32,
    step: 1,
    group: "execution",
  },
  {
    key: "loopMaxTotal",
    label: "Loop max total",
    description: "Maximum total loop sessions allowed",
    type: "number",
    default: 20,
    min: 0,
    max: 100,
    step: 1,
    group: "loops",
  },
  {
    key: "loopReservedInteractive",
    label: "Loop reserved interactive slots",
    description: "Slots reserved for interactive sessions (loops cannot use them)",
    type: "number",
    default: 4,
    min: 0,
    max: 20,
    step: 1,
    group: "loops",
  },
  {
    key: "ciAutoFix",
    label: "CI auto-fix",
    description: "Automatically spawn a fix session when CI fails",
    type: "boolean",
    default: false,
    group: "ci",
  },
  {
    key: "quotaRetryBudget",
    label: "Quota retry budget",
    description: "Number of retries on quota exhaustion before failing",
    type: "number",
    default: 3,
    min: 0,
    max: 10,
    step: 1,
    group: "execution",
  },
  {
    key: "memoryMcpEnabled",
    label: "Memory MCP enabled",
    description: "Enable the in-process memory MCP server",
    type: "boolean",
    default: true,
    group: "memory",
  },
  {
    key: "qualityTimeoutMs",
    label: "Quality check timeout (ms)",
    description: "Maximum time for each quality check command",
    type: "number",
    default: 300000,
    min: 5000,
    max: 3600000,
    step: 1000,
    group: "quality",
  },
  {
    key: "pushNotifyOnAttention",
    label: "Push notify on attention",
    description: "Send push notifications when a session needs attention",
    type: "boolean",
    default: true,
    group: "notifications",
  },
  {
    key: "judgeRubricDefault",
    label: "Default judge rubric",
    description: "Default rubric for variant judge evaluation",
    type: "string",
    default: "Favor correctness first, then minimality, then clarity.",
    group: "variants",
  },
  {
    key: "sseHeartbeatSec",
    label: "SSE heartbeat interval (seconds)",
    description: "How often to send SSE ping frames",
    type: "number",
    default: 25,
    min: 5,
    max: 120,
    step: 1,
    group: "transport",
    requiresRestart: true,
  },
  {
    key: "rebaseAutoResolverEnabled",
    label: "Rebase auto-resolver enabled",
    description: "Automatically spawn a rebase resolver session on conflict",
    type: "boolean",
    default: true,
    group: "execution",
  },
  {
    key: "landingDefaultStrategy",
    label: "Default landing strategy",
    description: "Default merge strategy when landing a session",
    type: "enum",
    default: "squash",
    enumValues: ["merge", "squash", "rebase"],
    group: "execution",
  },
  {
    key: "autoCommitOnCompletion",
    label: "Auto-commit on completion",
    description: "Automatically commit worktree changes when a session completes successfully",
    type: "boolean",
    default: true,
    group: "execution",
  },
];

export const runtimeConfigSchema: RuntimeConfigSchema = {
  groups: [
    { id: "execution", label: "Execution" },
    { id: "loops", label: "Loops" },
    { id: "ci", label: "CI" },
    { id: "quality", label: "Quality" },
    { id: "memory", label: "Memory" },
    { id: "notifications", label: "Notifications" },
    { id: "variants", label: "Variants" },
    { id: "transport", label: "Transport" },
  ],
  fields,
};
